CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(19, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_account_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE money_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_money_transfer_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_transfer_from_account FOREIGN KEY (from_account_id) REFERENCES account (id),
    CONSTRAINT fk_transfer_to_account FOREIGN KEY (to_account_id) REFERENCES account (id),
    CONSTRAINT chk_transfer_different_accounts CHECK (from_account_id <> to_account_id),
    CONSTRAINT chk_transfer_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_transfer_status CHECK (status = 'COMPLETED')
);

CREATE INDEX idx_transfer_from_account_id ON money_transfer (from_account_id);
CREATE INDEX idx_transfer_to_account_id ON money_transfer (to_account_id);
CREATE INDEX idx_transfer_status ON money_transfer (status);
